# fullnameOverride: connector-backend
nameOverride: connector-backend
replicaCount: 2

configMap:
  aviliable: false

image:
  repository: connector-backend-repository
  pullPolicy: IfNotPresent
  tag: latest-tag
  ports:
    containerPort: 3010

service:
  metadata:
    name: connector-backend
  type: NodePort
  port: 80
  targetPort: 3010
  name: web
  selector:
    app.kubernetes.io/name: connector-backend

deployment:
  metadata:
    name: connector-backend
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: connector-backend
    template:
      metadata:
        labels:
          logging: enabled
          app.kubernetes.io/name: connector-backend

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 90

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/group.name: connector
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:910398866891:certificate/8d2b6245-3288-4ede-9785-bab97ec5085a
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'

    
  hosts:
    - host: qa.backend.connector.grambell.com
      paths:
        - pathType: Prefix
          path: "/"
          worker:
            service:
              name: connector-backend
              port:
                number: 80

serviceMonitor:
  enabled: true
  name: connector-backend-service-monitor
  labels:
    app: connector-backend
  spec:
    selector:
      matchLabels:
        app: connector-backend
    endpoints:
    - port: web
      path: /api/metrics
