# fullnameOverride: connector-backend
nameOverride: 
namespace: 
replicaCount: 

image:
  repository: 
  pullPolicy: 
  tag:  # Rename from the pipeline
  ports:
    containerPort:

service:
  metadata:
    name:
  type: NodePort
  port: 80
  targetPort: 80
  selector:
    app.kubernetes.io/name:

deployment:
  metadata:
    namespace:
    name:
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: 
    template:
      metadata:
        labels:
          logging: enabled # For ELK Logging
          app.kubernetes.io/name: 

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 90

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: 
    
  hosts:
    - host: 
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: 
              port:
                number: 80

serviceMonitor:
  enabled: true
  name: service-monitor
  labels:
    team: backend
  spec:
    selector:
      matchLabels:
        app: connector-backend
    endpoints:
    - port: web

