{{- if .Values.configMap.aviliable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels: 
    {{- include "..labels" . | nindent 4 -}}
{{- with .Values.configMap.data }}
data: 
    {{- toYaml . | nindent 2}}
{{- end }}
{{- end -}}
