apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
          - name: index
            mountPath: '/usr/share/nginx/html'
          - name: test
            mountPath: '/tmp'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: index
          configMap: 
            name: {{.Values.configMap.name}}
            items: 
            - key: "index.html"
              path: "index.html"

        - name: test
          configMap: 
            name: {{.Values.configMap.name}}
            items: 
            - key: "test.html"
              path: "test.html"
          
          
      # {{- with .Values.nodeSelector }}
      # nodeSelector:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # {{- with .Values.affinity }}
      # affinity:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # {{- with .Values.tolerations }}
      # tolerations:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
