apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.configMap.aviliable }}
          volumeMounts:
              {{- range $name, $value := .Values.configMap }}
                {{- if eq $value.as "volume" }}
                - name: {{ $name }}-volume
                  mountPath: {{ quote $value.mountPath }}
                {{- end }}
              {{- end }}
            {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.configMap.aviliable }}
        {{- range $name, $value := .Values.configMap }}
          {{- if eq $value.as "volume" }}
          - name: {{ $name }}-volume
            mountPath: {{ quote $value.mountPath }}
            configMap:
              name: {{ $name }}
          {{- end }}
        {{- end }}
      {{- end}}
